### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [IlliaShev/pgn_parser#1]
Student: Шевчик Ілля

Для прохідного:
! CLI:  ✔️
! Brief Description: ✔️
! Project Name:  ✔️
! Grammar Rules: ✔️
! Unit Tests: ✔️
! Core Files: ✔️

Для мааксимального:
File System: ✔️
Test Coverage: ✔️
Error Handling: ❌ Ніяких panic, expect, unwrap у коді
cargo fmt: ✔️
cargo clippy:  ❌ потрібно було розібратися з усіма warn. У твоєму випадку ти міг викорисатити Box
makefile: ✔️
Completeness: ❌
Including a diagram or grammar in the Readme.md: ✔️
Documentation: ❌
Publishing: ✔️

Курсова  може бути зарахована ✔️
Бал: 22/25

**Comment by NYBACHOK** [comment]
Привіт. Напиши чи погодуєшся з оцінкою

**Comment by IlliaShev** [comment]
Привіт. З оцінкою погоджуюсь
